### ISSUE TITLE
Can we implement Setoid?

### ISSUE THREAD

**Issue by jongold** [jongold/further#3]
The original RFC implemented

##### `#equals :: Style a ~> Style a -> Boolean`		
[setoid](FL:setoid)		
```js		
// TODO: maybe the equality should be checked AFTER resolution?		
		
Style.of({ color: 'red' }).equals(Style.of({ color: 'red' }))		
// true		
		
Style.of({ color: 'red' }).equals(Style.of({ color: 'blue' }))		
// false		
		
```

idk if we can check equality for functions that haven't been resolved yet —
```js
Style(props => ({ color: props.color })).equals(Style.equals(props => ({ props.color })))
```
doesn't really make sense…

**Comment by buzzdecafe** [comment]
> idk if we can check equality for functions that haven't been resolved yet —

No, you cannot do that in a general way. 
https://en.wikipedia.org/wiki/Rice%27s_theorem
